### ISSUE TITLE
Button in game leads to malicious website.

### ISSUE THREAD

**Issue by itscharlie0110** [aldidoanta/TicTacToe-MCTS#2] opened 2023-03-14 00:19 UTC
In the "Introduction window" that pops up when you first open the game, there is a part that says "A quick reference to MCTS". When you go to the link next to it, it redirects to a malicious website. Just thought I would let people know.

**Comment by aldidoanta** [comment] 2023-03-14 01:48
Hi @itscharlie0110, thanks for pointing out the issue! [This line](https://github.com/aldidoanta/TicTacToeMCTS/blob/master/Assets/Scenes/gameplayScene.unity#L6069) should be the root cause, where http://mcts.ai is a dead link now. The URL should be replaced by the one I use in `README.md`.

The game has to be recompiled, and the new build has to be pushed to the `gh-pages` branch. I'll try to install Unity again and see if a 7.5-year project can be updated using the latest Unity 😆 .

**Comment by itscharlie0110** [comment] 2023-03-15 07:19
Alright! Thanks for the fix :)

Good luck on the update xD

**Comment by aldidoanta** [comment] 2023-03-16 11:33
I reopened this issue since it hasn't been fixed yet. The open issue also serves as a reminder to me to work on it.

I'll close this issue once the fix has been deployed.

**Comment by itscharlie0110** [comment] 2023-03-17 02:48
Oh, alright!

**Comment by aldidoanta** [comment] 2023-03-18 01:40
Ok, it turns out I can still use the legacy version of Unity (5.2.1). The issue has been fixed!

**Closed as completed by aldidoanta** 2023-03-18 01:40 UTC
